#!/usr/bin/env python3
"""Regenerates apps/catalog.json from PlatformIO build outputs under apps/*/.pio/build/.

Usage:
    python3 tools/make_catalog.py                  # write apps/catalog.json from the Mac build dirs
    python3 tools/make_catalog.py --check          # exit 1 if apps/catalog.json is stale
    python3 tools/make_catalog.py --ci-matrix      # JSON array = build matrix of .github/workflows/catalog.yml
    python3 tools/make_catalog.py --bins-root DIR --out DIR/catalog.json
                                                   # index CI artifacts laid out as DIR/<name>-<env>/<file>

The same upstream commit builds to a different firmware.bin on the Mac and on a GitHub runner (absolute source
paths end up in the binary), so published hashes must come from ONE builder: the catalog workflow rebuilds every
CI-buildable entry on runners and --bins-root indexes THOSE bins (built_by/source_ref/ci recorded per entry).
The default path (Mac build dirs, no extra fields) is unchanged so the --check gate keeps working locally.
"""
import argparse
import functools
import hashlib
import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
CATALOG_PATH = REPO_ROOT / "apps" / "catalog.json"

# boot_app0.bin is a fixed toolchain file (arduino-esp32 core), not a per-app
# build output; every entry here uses the default_8MB.csv partition table,
# whose otadata slot at 0xe000 needs it (see docs/FLASHING.md).
BOOT_APP0 = (
    Path.home()
    / ".platformio"
    / "packages"
    / "framework-arduinoespressif32"
    / "tools"
    / "partitions"
    / "boot_app0.bin"
)

# (offset, filename, required) for every entry's bin parts, in flash order.
PARTS = [
    (0x0, "bootloader.bin"),
    (0x8000, "partitions.bin"),
    (0xE000, None),  # boot_app0.bin, resolved via BOOT_APP0 below
    (0x10000, "firmware.bin"),
]

# Entries with "ci": False have a source only this Mac can see (pense-bem's private repo): the workflow skips
# them and --bins-root falls back to their Mac build dir. Everything else is CI-buildable, see ci_kind().
APPS = [
    {
        "name": "pense-bem",
        "board": "m5stack-stamps3",
        "env": "m5cardputer",
        "build_dir": "apps/pense-bem/.pio/build/m5cardputer",
        "description": "Pense-Bem rebuilt against the droidputter shim, real ST7789 panel + physical keyboard tee'd over USB-CDC.",
        "source_repo": "/Users/fcavalcanti/dev/m5/cardputter-pense-pem",
        "license": "unlicensed (private repo, Felipe Cavalcanti)",
        "ci": False,
    },
    {
        "name": "pense-bem",
        "board": "m5stack-stamps3",
        "env": "m5cardputer-virtual",
        "build_dir": "apps/pense-bem/.pio/build/m5cardputer-virtual",
        "description": "Pense-Bem on Panel_Droidputter (no physical display driven): the phone is the only screen.",
        "source_repo": "/Users/fcavalcanti/dev/m5/cardputter-pense-pem",
        "license": "unlicensed (private repo, Felipe Cavalcanti)",
        "ci": False,
    },
    {
        "name": "m5-example",
        "board": "m5stack-stamps3",
        "env": "m5cardputer",
        "build_dir": "apps/m5-example/.pio/build/m5cardputer",
        "description": "M5Cardputer library's own Basic/keyboard/inputText example rebuilt against the shim, unmodified.",
        "source_repo": "https://github.com/m5stack/M5Cardputer.git",
        "license": "MIT (m5stack/M5Cardputer)",
    },
    {
        "name": "m5-example",
        "board": "m5stack-sticks3",
        "env": "m5stack-sticks3",
        "build_dir": "apps/m5-example/.pio/build/m5stack-sticks3",
        "description": "Same inputText example rebuilt for the M5Stack StickS3 (ESP32-S3-PICO-1-N8R8, PSRAM opi).",
        "source_repo": "https://github.com/m5stack/M5Cardputer.git",
        "license": "MIT (m5stack/M5Cardputer)",
    },
    # Catalog apps generated by tools/overlay.py from bmorcelli's Launcher list (unchanged sources).
    {
        "name": "pigtail",
        "board": "m5stack-stamps3",
        "env": "m5cardputer",
        "build_dir": "apps/pigtail/.pio/build/m5cardputer",
        "description": "Pigtail (BLE tracker/glasses detector, NimBLE) rebuilt via tools/overlay.py. KNOWN: reboot-loops on the Cardputer ADV (interrupt WDT at boot, 2026-09-03) -- flashes fine, does not run yet.",
        "source_repo": "https://github.com/benbaker76/Pigtail.git",
        "license": "MIT (benbaker76/Pigtail)",
    },
    {
        "name": "stellar-map",
        "board": "m5stack-stamps3",
        "env": "m5cardputer",
        "build_dir": "apps/stellar-map/.pio/build/m5cardputer",
        "description": "stellar-map (planetarium star map for the Cardputer ADV) rebuilt against the shim via tools/overlay.py.",
        "source_repo": "https://github.com/wisnc/stellar-map.git",
        "license": "none declared (wisnc/stellar-map)",
    },
    {
        "name": "m5porkchop",
        "board": "m5stack-stamps3",
        "env": "m5cardputer",
        "build_dir": "apps/m5porkchop/.pio/build/m5cardputer",
        "description": "M5PORKCHOP (wardriving companion, NimBLE + GPS) rebuilt against the shim via tools/overlay.py.",
        "source_repo": "https://github.com/0ct0sec/M5PORKCHOP.git",
        "license": "MIT (0ct0sec/M5PORKCHOP)",
    },
    {
        "name": "cardputer-iss-tracker",
        "board": "m5stack-stamps3",
        "env": "m5cardputer",
        "build_dir": "apps/cardputer-iss-tracker/.pio/build/m5cardputer",
        "description": "ISS tracker (SGP4 orbit, WiFi TLE fetch; credentials.h seeded from the repo example) rebuilt via tools/overlay.py.",
        "source_repo": "https://github.com/adammelancon/cardputer-iss-tracker.git",
        "license": "MIT (adammelancon/cardputer-iss-tracker)",
    },
    {
        "name": "bluetooth-keyboard-mouse-emulator",
        "board": "m5stack-stamps3",
        "env": "m5cardputer",
        "build_dir": "apps/bluetooth-keyboard-mouse-emulator/.pio/build/m5cardputer",
        "description": "BLE keyboard/mouse emulator (the Cardputer as a Bluetooth HID) rebuilt via tools/overlay.py.",
        "source_repo": "https://github.com/geo-tp/Bluetooth-Keyboard-Mouse-Emulator.git",
        "license": "MIT (geo-tp/Bluetooth-Keyboard-Mouse-Emulator)",
    },
    {
        "name": "m5cardputer-audio-stream-server",
        "board": "m5stack-stamps3",
        "env": "m5cardputer",
        "build_dir": "apps/m5cardputer-audio-stream-server/.pio/build/m5cardputer",
        "description": "Audio stream server (mic over WiFi) rebuilt via tools/overlay.py.",
        "source_repo": "https://github.com/geo-tp/M5Cardputer-Audio-Stream-Server.git",
        "license": "MIT (geo-tp/M5Cardputer-Audio-Stream-Server)",
    },
    {
        "name": "ultimate-remote",
        "board": "m5stack-stamps3",
        "env": "m5cardputer",
        "build_dir": "apps/ultimate-remote/.pio/build/m5cardputer",
        "description": "Ultimate Remote (IR/BLE/WiFi remote, flash 98% of the 8 MB app partition) rebuilt via tools/overlay.py.",
        "source_repo": "https://github.com/geo-tp/Ultimate-Remote.git",
        "license": "NOASSERTION (geo-tp/Ultimate-Remote)",
    },    {
        "name": "m5-palnagotchi",
        "board": "m5stack-stamps3",
        "env": "m5cardputer",
        "build_dir": "apps/m5-palnagotchi/.pio/build/m5cardputer",
        "description": "Palnagotchi (Pwnagotchi companion, .ino, libs inferred) rebuilt via tools/overlay.py.",
        "source_repo": "https://github.com/viniciusbo/m5-palnagotchi.git",
        "license": "MIT (viniciusbo/m5-palnagotchi)",
    },
    {
        "name": "cardputer",
        "board": "m5stack-stamps3",
        "env": "m5cardputer",
        "build_dir": "apps/cardputer/.pio/build/m5cardputer",
        "description": "VolosR/Cardputer sketches (.ino) rebuilt via tools/overlay.py.",
        "source_repo": "https://github.com/VolosR/Cardputer.git",
        "license": "none declared (VolosR/Cardputer)",
    },
    {
        "name": "m5cardputer_audiospectrum",
        "board": "m5stack-stamps3",
        "env": "m5cardputer",
        "build_dir": "apps/m5cardputer_audiospectrum/.pio/build/m5cardputer",
        "description": "Audio spectrum analyser on the Cardputer mic (.ino) rebuilt via tools/overlay.py.",
        "source_repo": "https://github.com/cyberwisk/m5Cardputer_audiospectrum.git",
        "license": "GPL-3.0 (cyberwisk/m5Cardputer_audiospectrum)",
    },
    {
        "name": "cardputer-system-monitor",
        "board": "m5stack-stamps3",
        "env": "m5cardputer",
        "build_dir": "apps/cardputer-system-monitor/.pio/build/m5cardputer",
        "description": "System monitor (.ino) rebuilt via tools/overlay.py.",
        "source_repo": "https://github.com/gdantas04/Cardputer-System-Monitor.git",
        "license": "none declared (gdantas04/Cardputer-System-Monitor)",
    },
    {
        "name": "miniacid",
        "board": "m5stack-stamps3",
        "env": "m5cardputer",
        "build_dir": "apps/miniacid/.pio/build/m5cardputer",
        "description": "miniacid (TB-303 style acid synth, .ino + src/) rebuilt via tools/overlay.py.",
        "source_repo": "https://github.com/urtubia/miniacid.git",
        "license": "MIT (urtubia/miniacid)",
    },
    {
        "name": "m5cardputer_webradio",
        "board": "m5stack-stamps3",
        "env": "m5cardputer",
        "build_dir": "apps/m5cardputer_webradio/.pio/build/m5cardputer",
        "description": "Web radio (WiFi internet radio to the Cardputer speaker, .ino) rebuilt via tools/overlay.py.",
        "source_repo": "https://github.com/cyberwisk/M5Cardputer_WebRadio.git",
        "license": "none declared (cyberwisk/M5Cardputer_WebRadio)",
    },
    {
        "name": "cardputergpsmap",
        "board": "m5stack-stamps3",
        "env": "m5cardputer",
        "build_dir": "apps/cardputergpsmap/.pio/build/m5cardputer",
        "description": "GPS map (TinyGPS++ + JPEG tiles, .ino) rebuilt via tools/overlay.py.",
        "source_repo": "https://github.com/lunarc3/CardputerGPSMap.git",
        "license": "GPL-3.0 (lunarc3/CardputerGPSMap)",
    },
    {
        "name": "tiny-journal",
        "board": "m5stack-stamps3",
        "env": "m5cardputer",
        "build_dir": "apps/tiny-journal/.pio/build/m5cardputer",
        "description": "Tiny Journal (notes with BLE keyboard, NimBLE 2.x, .ino) rebuilt via tools/overlay.py.",
        "source_repo": "https://github.com/joejee90/Tiny-Journal.git",
        "license": "none declared (joejee90/Tiny-Journal)",
    },
]

GITHUB_URL = re.compile(r"^https://github\.com/([\w.-]+)/([\w.-]+?)(?:\.git)?/?$")
# First comment line of every apps/<name>/platformio.ini that tools/overlay.py writes (ENV_TEMPLATE); the
# hand-written recipes (m5-example, pense-bem, gps-demo) do not carry it.
OVERLAY_MARKER = "generated by tools/overlay.py"


def sha256_of(path: Path) -> str:
    h = hashlib.sha256()
    h.update(path.read_bytes())
    return h.hexdigest()


@functools.lru_cache(maxsize=None)
def shim_commit() -> str:
    """Last commit touching shim/ -- a build's identity together with its firmware sha256; stable until
    the shim changes (a plain HEAD would churn the catalog on every commit). Needs git history: the
    catalog workflow checks out with fetch-depth 0."""
    import subprocess
    r = subprocess.run(["git", "log", "-1", "--format=%h", "--", "shim/"], cwd=REPO_ROOT, capture_output=True, text=True)
    return r.stdout.strip() or "unknown"


# Where the phone downloads a shim build's parts from (the APK bundles no binaries since 2026-09-04).
# Placeholders: {name} {env} {file} {sha256}. None = no url yet: the entry lists but cannot be flashed from
# the phone -- set once the hosting decision (GitHub release / branch / LauncherHub upload) is taken.
BIN_URL_TEMPLATE = None


def github_slug(url: str):
    m = GITHUB_URL.match(url)
    return f"{m.group(1)}/{m.group(2)}" if m else None


def ci_kind(app: dict):
    """How .github/workflows/catalog.yml builds this entry -> (kind, reason).
    "overlay": `python3 tools/overlay.py <owner/repo> --name <name> --build` -- regenerates the ini from upstream
               HEAD on purpose (the catalog tracks upstream) and builds env m5cardputer, the only env it builds.
    "inrepo":  `bash shim/apply.sh apps/<name> && cd apps/<name> && pio run -e <env>` -- a hand-written ini whose
               sources live in this repo (m5-example: the vendored sketch under shim/upstream/).
    None:      not CI-buildable, reason says why (printed by --ci-matrix, recorded as "ci": false)."""
    if app.get("ci", True) is False:
        return None, "ci: false (source only this Mac can see)"
    if github_slug(app["source_repo"]) is None:
        return None, f"source_repo is not a github url: {app['source_repo']}"
    ini = REPO_ROOT / "apps" / app["name"] / "platformio.ini"
    if not ini.is_file():
        return None, f"missing {ini.relative_to(REPO_ROOT)}"
    if OVERLAY_MARKER in ini.read_text():
        if app["env"] != "m5cardputer":
            return None, f"overlay.py --build only builds env m5cardputer, not {app['env']}"
        return "overlay", ""
    return "inrepo", ""


def ci_matrix() -> list:
    items = []
    for app in APPS:
        kind, reason = ci_kind(app)
        if kind is None:
            print(f"make_catalog: --ci-matrix skip {app['name']}/{app['env']}: {reason}", file=sys.stderr)
            continue
        items.append({
            "name": app["name"],
            "env": app["env"],
            "kind": kind,
            "repo": github_slug(app["source_repo"]) if kind == "overlay" else None,
            "app_dir": f"apps/{app['name']}",
        })
    return items


def part_paths(base: Path, boot_app0: Path) -> list:
    return [(offset, boot_app0 if filename is None else base / filename) for offset, filename in PARTS]


def build_entry(app: dict, bins_root=None) -> dict:
    """Default: parts from the Mac build dir, missing file = FileNotFoundError (the --check gate's contract).
    --bins-root DIR: parts from DIR/<name>-<env>/ (the workflow's artifact layout, boot_app0.bin included), else
    the Mac build dir when it is complete, else FileNotFoundError; the entry gains built_by ("ci" | "mac"),
    source_ref (upstream commit from DIR/<name>-<env>/build.json) and ci (CI-buildable at all)."""
    build_dir = REPO_ROOT / app["build_dir"]
    paths, built_by, build_json = part_paths(build_dir, BOOT_APP0), None, {}
    if bins_root is not None:
        ci_dir = bins_root / f"{app['name']}-{app['env']}"
        ci_paths = part_paths(ci_dir, ci_dir / "boot_app0.bin")
        if all(p.is_file() for _, p in ci_paths):
            paths, built_by = ci_paths, "ci"
            if (ci_dir / "build.json").is_file():
                try:
                    build_json = json.loads((ci_dir / "build.json").read_text())
                except ValueError:
                    print(f"make_catalog: {ci_dir.name}/build.json is not JSON, source_ref left null", file=sys.stderr)
        elif all(p.is_file() for _, p in paths):
            built_by = "mac"
        else:
            raise FileNotFoundError(f"{app['name']}/{app['env']}: no complete parts under {bins_root.name}/{ci_dir.name}/ nor {app['build_dir']}")
    parts = []
    for offset, path in paths:
        if not path.is_file():
            raise FileNotFoundError(f"{app['name']}/{app['env']}: missing {path}")
        part = {
            "offset": hex(offset),
            "file": path.name,
            "size": path.stat().st_size,
            "sha256": sha256_of(path),
        }
        if BIN_URL_TEMPLATE:
            part["url"] = BIN_URL_TEMPLATE.format(name=app["name"], env=app["env"], file=path.name, sha256=part["sha256"])
        parts.append(part)
    entry = {
        "name": app["name"],
        "board": app["board"],
        "env": app["env"],
        "description": app["description"],
        "source_repo": app["source_repo"],
        "license": app["license"],
        "build_dir": app["build_dir"],
        "parts": parts,
        "shim_commit": shim_commit(),
        "source": "droidputter",   # a shim rebuild: the phone is the screen (vs "launcherhub" prebuilt, flash only)
        "mirror": True,
    }
    if bins_root is not None:
        entry["built_by"] = built_by
        # overlay builds: tools/overlay.py's JSON line (upstream_commit); in-repo builds: the workflow's own
        # build.json (source_ref = the droidputter commit that holds the vendored sources)
        entry["source_ref"] = build_json.get("upstream_commit") or build_json.get("source_ref")
        entry["ci"] = ci_kind(app)[0] is not None
    return entry


def generate(bins_root=None) -> list:
    if bins_root is None:
        return [build_entry(app) for app in APPS]
    catalog = []
    for app in APPS:
        try:
            entry = build_entry(app, bins_root)
        except FileNotFoundError as exc:
            print(f"make_catalog: dropped {exc}", file=sys.stderr)
            continue
        fw = next(p for p in entry["parts"] if p["file"] == "firmware.bin")
        print(f"indexed {entry['name']}/{entry['env']} built_by={entry['built_by']} source_ref={entry['source_ref']} firmware_sha256={fw['sha256'][:12]}")
        catalog.append(entry)
    return catalog


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="exit 1 if the catalog file is stale instead of writing it")
    ap.add_argument("--ci-matrix", action="store_true", help="print the workflow build matrix (one-line JSON array) and exit")
    ap.add_argument("--bins-root", metavar="DIR", type=Path, help="read parts from DIR/<name>-<env>/ (CI artifact layout) instead of the build dirs")
    ap.add_argument("--out", metavar="FILE", type=Path, help="catalog file to write / check (default apps/catalog.json)")
    args = ap.parse_args()

    if args.ci_matrix:
        print(json.dumps(ci_matrix()))   # one line: the workflow puts it straight into $GITHUB_OUTPUT
        return 0

    bins_root = args.bins_root.resolve() if args.bins_root else None
    out = args.out.resolve() if args.out else CATALOG_PATH
    try:
        catalog = generate(bins_root)
    except FileNotFoundError as exc:
        print(f"make_catalog: {exc}", file=sys.stderr)
        return 1
    if not catalog:
        print("make_catalog: nothing indexed", file=sys.stderr)
        return 1

    text = json.dumps(catalog, indent=2) + "\n"

    if args.check:
        if not out.is_file():
            print(f"make_catalog: {out} does not exist", file=sys.stderr)
            return 1
        current = out.read_text()
        if current != text:
            print(f"make_catalog: {out} is stale, run without --check to regenerate", file=sys.stderr)
            return 1
        print("catalog ok")
        return 0

    out.write_text(text)
    dropped = f", {len(APPS) - len(catalog)} dropped" if bins_root is not None else ""
    print(f"wrote {out} ({len(catalog)} entries{dropped})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
